### PR TITLE
OpenCV 3.3.0 update

### PR DESCRIPTION
**Pull request by denismakogon**

### CODE REVIEW

**Comment by denismakogon** [comment]
```
Python 3.6.2 (default, Aug 29 2017, 05:52:11) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'3.3.0'
```

**Comment by janza** [comment]
Thanks!

**Comment by denismakogon** [comment]
No problem. Can you push newer image asap?

**Comment by janza** [comment]
Yes, docker hub build is automated so as soon as the build finishes new image will be available for pulling.

**Pull request merged**
